spring.datasource.url=jdbc:mariadb://${DB_HOST:gateway01.ap-southeast-1.prod.aws.tidbcloud.com}:${DB_PORT:4000}/${DB_NAME:Messing}?sslMode=${DB_SSL_MODE:trust}&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USER:u9eun8QG2iP1vYL.root}
spring.datasource.password=${DB_PASSWORD:8i1q3U0wvzxdMOvY}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# Storage: Cloudinary
app.storage.provider=cloudinary
app.cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:duekrpmsl}
app.cloudinary.api-key=${CLOUDINARY_API_KEY:mediaflows_19d9ce46-4e60-43f6-8655-5b1046e833fa}
app.cloudinary.api-secret=${CLOUDINARY_API_SECRET:tTwK2_oILifUgiyisAgw2ssZTqo}
