
spring.datasource.url=jdbc:mariadb://${DB_HOST:gateway01.ap-southeast-1.prod.aws.tidbcloud.com}:${DB_PORT:4000}/${DB_NAME:Messing}?sslMode=verify-full
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# Storage: Cloudinary
app.storage.provider=${APP_STORAGE_PROVIDER:cloudinary}
app.cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
app.cloudinary.api-key=${CLOUDINARY_API_KEY}
app.cloudinary.api-secret=${CLOUDINARY_API_SECRET}
